security:
  oauth2:
    client:
      client-id: 561808189472626
      client-secret: a400887cb8f47647b9ccf6abeceb43f6

      access-token-uri: https://www.facebook.com/oauth/access_token
#      access-token-uri: https://github.com/login/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
#      user-authorization-uri: https://github.com/login/oauth/authorize
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
    resource:
      #user-info-uri: http://graph.facebook.com/mer
      user-info-uri: https://api.github.com/user

server:
  port: 8081